name: CI

on: pull_request

jobs:
  yath:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ '5.36', '5.34' ]
    container:
      image: perl:${{ matrix.perl }}
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: cpanm --quite --notest --installdeps .
      - run: cpanm --quite --notest App::Yath
      - run: yath test --qvf t/

  prove:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.12', '5.14']
    container:
      image: perl:${{ matrix.perl }}
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: cpanm --quite --notest --installdeps .
      - run: cpanm --quite --notest App::Prove
      - run: prove -lrv t

  prove_legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.8', '5.10']
    container:
      image: perl:${{ matrix.perl }}
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: cpanm --quite --notest Pod::Man@4.10 Test::Deep@1.130 App::Prove
      - run: cpanm --quite --notest --installdeps .
      - run: prove -lrv t
