name: CI

on: pull_request

jobs:
  mbtiny-dist:
    runs-on: ubuntu-latest
    container:
      image: perl:5.38
    steps:
      - uses: actions/checkout@v4
      - run: cpanm --quiet --notest App::ModuleBuildTiny
      - run: mbtiny distdir
      - run: echo ./App-perlbrew-*
      - uses: actions/upload-artifact@v4
        with:
          name: App-perlbrew-distdir
          path: ./App-perlbrew-*
          retention-days: 5

  cpanm-dist:
    needs: mbtiny-dist
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "macos-13"]
        version: ["5.40","5.38", "5.18"]
    name: cpanm-dist-perl-${{ matrix.version }}-${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1.31.3
        with:
          perl-version: ${{ matrix.version }}
      - uses: actions/download-artifact@v4
        with:
          name: App-perlbrew-distdir
      - run: echo ./App-perlbrew-*
      - run: cpanm --verbose ./App-perlbrew-*

  cpanm-dist-in-container:
    needs: mbtiny-dist
    strategy:
      matrix:
        version: ["5.41"]
    name: cpanm-dist-perl-${{ matrix.version }}
    runs-on: ubuntu-latest
    container:
      image: perl:${{ matrix.version }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: App-perlbrew-distdir
      - run: echo ./App-perlbrew-*
      - run: cpanm --verbose ./App-perlbrew-*

  e2e:
    name: e2e
    runs-on: ubuntu-latest
    container:
      image: perl:5.40
    steps:
      - uses: actions/checkout@v4
      - run: |
          apt update
          apt install -y zsh
      - run: ./test-e2e/run.zsh

  e2eMacos:
    name: e2eMacos
    runs-on: macos-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1.31.3
        with:
          perl-version: "5.40"
      - uses: actions/checkout@v4
      - run: ./test-e2e/run.zsh
