name: CI

on: pull_request

jobs:
  mbtiny-dist:
    runs-on: ubuntu-latest
    container:
      image: perl:5.38
    steps:
      - uses: actions/checkout@v2
      - run: cpanm --quiet --notest App::ModuleBuildTiny
      - run: mbtiny dist
      - run: echo ./App-perlbrew-*.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: App-perlbrew-tarball
          path: ./App-perlbrew-*.tar.gz
          retention-days: 5

  cpanm-dist:
    needs: mbtiny-dist
    strategy:
      matrix:
        version: ["5.39", "5.38", "5.36", "5.34", "5.18"]
    name: cpanm-dist-perl-${{ matrix.version }}
    runs-on: ubuntu-latest
    container:
      image: perl:${{ matrix.version }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: App-perlbrew-tarball
      - run: echo ./App-perlbrew-*.tar.gz
      - run: cpanm --verbose ./App-perlbrew-*.tar.gz
