name: CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    steps:
      - name: install dependencies
        run: |
          apt install -y git
          cpanm --notest --quiet App::PerlNitpick
      - uses: actions/checkout@v2
      - uses: gugod/action-perlcritic@fun
        with:
          directory: "lib script t dev-bin"
      - name: run perlnitpick
        run: perlnitpick --inplace --rules=RemoveTrailingWhitespace,RemoveUnusedVariables,RemoveUnusedInclude,RemoveUnusedImport .
      - name: suggester
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: perlnitpick

  yath:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ '5.36', '5.34' ]
    container:
      image: perl:${{ matrix.perl }}
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: cpanm --quite --notest --installdeps .
      - run: cpanm --quite --notest App::Yath
      - run: yath test --qvf t/

  prove:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.12', '5.14']
    container:
      image: perl:${{ matrix.perl }}
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: cpanm --quite --notest --installdeps .
      - run: cpanm --quite --notest App::Prove
      - run: prove -lrv t

  prove_legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.8', '5.10']
    container:
      image: perl:${{ matrix.perl }}
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: cpanm --quite --notest Pod::Man@4.10 Test::Deep@1.130 App::Prove
      - run: cpanm --quite --notest --installdeps .
      - run: prove -lrv t
