dnf-install: &with-dnf-install
  dnf install -y zsh perl

fedora-init: *with-dnf-install

almalinux-init: *with-dnf-install

rockylinux-init: *with-dnf-install

ubuntu-init: |
  sudo apt-get update
  sudo apt-get install zsh

alpine-init: |
  apk add zsh perl
